FROM node:latest

# Configuração do diretório de trabalho
WORKDIR /app

# Copia o package.json e o package-lock.json para o container
COPY package*.json ./

# Instala as dependências
RUN npm ci --only=production

# Copia o código do projeto para o container
COPY . .

# Constrói a aplicação
RUN npm run build

# Expõe a porta 3000 para o acesso ao servidor
EXPOSE 3000

# Inicia o servidor de produção
CMD ["npm", "start"]
